## Preprocessing

In [26]:
# Install tensorflow
%pip install tensorflow

# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

# Import pandas and read the charity_data.csv from the provided cloud URL.
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

Requirement already satisfied: tensorflow in c:\users\corie\anaconda3\envs\dev\lib\site-packages (2.19.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: absl-py>=1.0.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (2.2.2)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (4.25.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (75.1.0)
Requirement already satisfied: six>=1.12.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (4.11.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (1.71.0)
Requirement already satisfied: tensorboard~=2.19.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (3.9.2)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (3.11.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorflow) (0.5.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.44.0)
Requirement already satisfied: rich in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from keras>=3.5.0->tensorflow) (13.7.1)
Requirement already satisfied: namex in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from keras>=3.5.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from keras>=3.5.0->tensorflow) (0.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2024.8.30)
Requirement already satisfied: markdown>=2.6.8 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorboard~=2.19.0->tensorflow) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (2.1.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from rich->keras>=3.5.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from rich->keras>=3.5.0->tensorflow) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\corie\anaconda3\envs\dev\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.0)

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [27]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN", "NAME"])

In [28]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [29]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [30]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_type_counts[application_type_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [31]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [32]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts[classification_counts > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [33]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts < 100].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [34]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, columns=["APPLICATION_TYPE", "CLASSIFICATION"], drop_first=True)
# Display the first few rows of the modified DataFrame
application_df.head()

,AFFILIATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,...,CLASSIFICATION_C1270,CLASSIFICATION_C1700,CLASSIFICATION_C2000,CLASSIFICATION_C2100,CLASSIFICATION_C2700,CLASSIFICATION_C3000,CLASSIFICATION_C4000,CLASSIFICATION_C5000,CLASSIFICATION_C7000,CLASSIFICATION_Other
0,Independent,ProductDev,Association,1,0,N,5000,1,True,False,...,False,False,False,False,False,False,False,False,False,False
1,Independent,Preservation,Co-operative,1,1-9999,N,108590,1,False,False,...,False,False,True,False,False,False,False,False,False,False
2,CompanySponsored,ProductDev,Association,1,0,N,5000,0,False,False,...,False,False,False,False,False,True,False,False,False,False
3,CompanySponsored,Preservation,Trust,1,10000-24999,N,6692,1,False,False,...,False,False,True,False,False,False,False,False,False,False
4,Independent,Heathcare,Trust,1,100000-499999,N,142590,1,False,False,...,False,False,False,False,False,False,False,False,False,False

In [35]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(columns=["IS_SUCCESSFUL"]).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, stratify=y)

In [36]:
# Ensure X_train and X_test are DataFrames and have no missing values
X_train = pd.DataFrame(X_train, columns=application_df.drop(columns=["IS_SUCCESSFUL"]).columns)  # Convert to DataFrame
X_test = pd.DataFrame(X_test, columns=application_df.drop(columns=["IS_SUCCESSFUL"]).columns)    # Similarly for X_test

# Convert categorical features to categorical dtype if not already
categorical_columns = X_train.select_dtypes(include=['object']).columns

# Apply one-hot encoding to categorical columns
X_train_encoded = pd.get_dummies(X_train, columns=categorical_columns, drop_first=True)
X_test_encoded = pd.get_dummies(X_test, columns=categorical_columns, drop_first=True)

# Ensure that the columns in X_train and X_test are aligned (they must have the same columns after encoding)
X_train_encoded, X_test_encoded = X_train_encoded.align(X_test_encoded, join='left', axis=1, fill_value=0)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler after ensuring that X_train only contains numeric data
X_scaler = scaler.fit(X_train_encoded)

# Scale the data
X_train_scaled = X_scaler.transform(X_train_encoded)
X_test_scaled = X_scaler.transform(X_test_encoded)

## Compile, Train and Evaluate the Model

In [37]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = X_train.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer
hidden_nodes_1 = 80
nn.add(tf.keras.layers.Dense(units=hidden_nodes_1, activation="relu", input_dim=number_input_features))

# Second hidden layer
hidden_nodes_2 = 30
nn.add(tf.keras.layers.Dense(units=hidden_nodes_2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

c:\Users\corie\anaconda3\envs\dev\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 80)             │         2,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 30)             │         2,430 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,621 (18.05 KB)

 Trainable params: 4,621 (18.05 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [40]:
# Ensure the input data has the correct shape
X_train_scaled_corrected = X_train_scaled[:, :number_input_features]

# Recompile the model to ensure no issues with variable creation
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled_corrected, y_train, epochs=100, shuffle=True, verbose=2)

Epoch 1/100
804/804 - 7s - 8ms/step - accuracy: 0.7016 - loss: 0.5970
Epoch 2/100
804/804 - 3s - 4ms/step - accuracy: 0.7013 - loss: 0.5972
Epoch 3/100
804/804 - 3s - 4ms/step - accuracy: 0.7017 - loss: 0.5966
Epoch 4/100
804/804 - 3s - 4ms/step - accuracy: 0.7015 - loss: 0.5965
Epoch 5/100
804/804 - 3s - 4ms/step - accuracy: 0.7019 - loss: 0.5967
Epoch 6/100
804/804 - 4s - 4ms/step - accuracy: 0.7023 - loss: 0.5967
Epoch 7/100
804/804 - 3s - 4ms/step - accuracy: 0.7017 - loss: 0.5964
Epoch 8/100
804/804 - 3s - 4ms/step - accuracy: 0.7016 - loss: 0.5966
Epoch 9/100
804/804 - 3s - 4ms/step - accuracy: 0.7013 - loss: 0.5966
Epoch 10/100
804/804 - 3s - 4ms/step - accuracy: 0.7011 - loss: 0.5965
Epoch 11/100
804/804 - 3s - 4ms/step - accuracy: 0.7016 - loss: 0.5965
Epoch 12/100
804/804 - 3s - 4ms/step - accuracy: 0.7020 - loss: 0.5965
Epoch 13/100
804/804 - 3s - 4ms/step - accuracy: 0.7018 - loss: 0.5963
Epoch 14/100
804/804 - 3s - 4ms/step - accuracy: 0.7017 - loss: 0.5963
Epoch 15/100
804/804 - 3s - 4ms/step - accuracy: 0.7017 - loss: 0.5963
Epoch 16/100
804/804 - 3s - 4ms/step - accuracy: 0.7017 - loss: 0.5962
Epoch 17/100
804/804 - 3s - 4ms/step - accuracy: 0.7019 - loss: 0.5965
Epoch 18/100
804/804 - 3s - 4ms/step - accuracy: 0.7016 - loss: 0.5963
Epoch 19/100
804/804 - 3s - 4ms/step - accuracy: 0.7018 - loss: 0.5963
Epoch 20/100
804/804 - 3s - 4ms/step - accuracy: 0.7020 - loss: 0.5964
Epoch 21/100
804/804 - 3s - 4ms/step - accuracy: 0.7024 - loss: 0.5966
Epoch 22/100
804/804 - 3s - 4ms/step - accuracy: 0.7017 - loss: 0.5960
Epoch 23/100
804/804 - 3s - 4ms/step - accuracy: 0.7013 - loss: 0.5965
Epoch 24/100
804/804 - 3s - 4ms/step - accuracy: 0.7019 - loss: 0.5959
Epoch 25/100
804/804 - 3s - 4ms/step - accuracy: 0.7018 - loss: 0.5961
Epoch 26/100
804/804 - 3s - 4ms/step - accuracy: 0.7023 - loss: 0.5965
Epoch 27/100
804/804 - 4s - 5ms/step - accuracy: 0.7018 - loss: 0.5961
Epoch 28/100
804/804 - 3s - 4ms/step - accuracy: 0.7019 - loss: 0.5962
Epoch 29/100
804/804 - 5s - 6ms/step - accuracy: 0.7010 - loss: 0.5961
Epoch 30/100
804/804 - 3s - 4ms/step - accuracy: 0.7019 - loss: 0.5960
Epoch 31/100
804/804 - 3s - 4ms/step - accuracy: 0.7018 - loss: 0.5960
Epoch 32/100
804/804 - 3s - 4ms/step - accuracy: 0.7019 - loss: 0.5960
Epoch 33/100
804/804 - 3s - 4ms/step - accuracy: 0.7015 - loss: 0.5959
Epoch 34/100
804/804 - 3s - 4ms/step - accuracy: 0.7011 - loss: 0.5961
Epoch 35/100
804/804 - 3s - 4ms/step - accuracy: 0.7010 - loss: 0.5961
Epoch 36/100
804/804 - 3s - 4ms/step - accuracy: 0.7022 - loss: 0.5961
Epoch 37/100
804/804 - 3s - 4ms/step - accuracy: 0.7020 - loss: 0.5958
Epoch 38/100
804/804 - 3s - 4ms/step - accuracy: 0.7020 - loss: 0.5963
Epoch 39/100
804/804 - 3s - 4ms/step - accuracy: 0.7023 - loss: 0.5959
Epoch 40/100
804/804 - 3s - 4ms/step - accuracy: 0.7018 - loss: 0.5959
Epoch 41/100
804/804 - 3s - 4ms/step - accuracy: 0.7023 - loss: 0.5958
Epoch 42/100
804/804 - 3s - 4ms/step - accuracy: 0.7022 - loss: 0.5960
Epoch 43/100
804/804 - 3s - 4ms/step - accuracy: 0.7016 - loss: 0.5958
Epoch 44/100
804/804 - 3s - 4ms/step - accuracy: 0.7019 - loss: 0.5959
Epoch 45/100
804/804 - 3s - 4ms/step - accuracy: 0.7021 - loss: 0.5962
Epoch 46/100
804/804 - 3s - 4ms/step - accuracy: 0.7021 - loss: 0.5959
Epoch 47/100
804/804 - 3s - 4ms/step - accuracy: 0.7014 - loss: 0.5960
Epoch 48/100
804/804 - 3s - 4ms/step - accuracy: 0.7022 - loss: 0.5958
Epoch 49/100
804/804 - 3s - 4ms/step - accuracy: 0.7022 - loss: 0.5960
Epoch 50/100
804/804 - 3s - 4ms/step - accuracy: 0.7017 - loss: 0.5959
Epoch 51/100
804/804 - 3s - 4ms/step - accuracy: 0.7021 - loss: 0.5962
Epoch 52/100
804/804 - 4s - 5ms/step - accuracy: 0.7020 - loss: 0.5961
Epoch 53/100
804/804 - 3s - 4ms/step - accuracy: 0.7020 - loss: 0.5959
Epoch 54/100
804/804 - 3s - 4ms/step - accuracy: 0.7018 - loss: 0.5959
Epoch 55/100
804/804 - 3s - 4ms/step - accuracy: 0.7021 - loss: 0.5958
Epoch 56/100
804/804 - 3s - 4ms/step - accuracy: 0.7022 - loss: 0.5959
Epoch 57/100
804/804 - 3s - 4ms/step - accuracy: 0.7019 - loss: 0.5956
Epoch 58/100
804/804 - 3s - 4ms/step - accuracy: 0.7018 - loss: 0.5960
Epoch 59/100
804/804 - 4s - 4ms/step - accuracy: 0.7017 - loss: 0.5956
Epoch 60/100
804/804 - 3s - 4ms/step - accuracy: 0.7022 - loss: 0.5963
Epoch 61/100
804/804 - 2s - 2ms/step - accuracy: 0.7023 - loss: 0.5958
Epoch 62/100
804/804 - 2s - 2ms/step - accuracy: 0.7021 - loss: 0.5958
Epoch 63/100
804/804 - 1s - 2ms/step - accuracy: 0.7017 - loss: 0.5958
Epoch 64/100
804/804 - 1s - 2ms/step - accuracy: 0.7019 - loss: 0.5958
Epoch 65/100
804/804 - 1s - 2ms/step - accuracy: 0.7019 - loss: 0.5958
Epoch 66/100
804/804 - 1s - 2ms/step - accuracy: 0.7022 - loss: 0.5958
Epoch 67/100
804/804 - 71s - 88ms/step - accuracy: 0.7024 - loss: 0.5958
Epoch 68/100
804/804 - 19s - 23ms/step - accuracy: 0.7018 - loss: 0.5957
Epoch 69/100
804/804 - 4s - 5ms/step - accuracy: 0.7016 - loss: 0.5960
Epoch 70/100
804/804 - 2s - 3ms/step - accuracy: 0.7024 - loss: 0.5955
Epoch 71/100
804/804 - 2s - 2ms/step - accuracy: 0.7021 - loss: 0.5957
Epoch 72/100
804/804 - 2s - 2ms/step - accuracy: 0.7021 - loss: 0.5956
Epoch 73/100
804/804 - 2s - 2ms/step - accuracy: 0.7022 - loss: 0.5955
Epoch 74/100
804/804 - 2s - 2ms/step - accuracy: 0.7023 - loss: 0.5958
Epoch 75/100
804/804 - 2s - 2ms/step - accuracy: 0.7020 - loss: 0.5958
Epoch 76/100
804/804 - 1s - 2ms/step - accuracy: 0.7021 - loss: 0.5955
Epoch 77/100
804/804 - 2s - 2ms/step - accuracy: 0.7021 - loss: 0.5960
Epoch 78/100
804/804 - 2s - 3ms/step - accuracy: 0.7019 - loss: 0.5956
Epoch 79/100
804/804 - 2s - 2ms/step - accuracy: 0.7023 - loss: 0.5957
Epoch 80/100
804/804 - 2s - 2ms/step - accuracy: 0.7019 - loss: 0.5955
Epoch 81/100
804/804 - 2s - 3ms/step - accuracy: 0.7016 - loss: 0.5956
Epoch 82/100
804/804 - 2s - 2ms/step - accuracy: 0.7018 - loss: 0.5957
Epoch 83/100
804/804 - 2s - 2ms/step - accuracy: 0.7016 - loss: 0.5964
Epoch 84/100
804/804 - 2s - 3ms/step - accuracy: 0.7019 - loss: 0.5985
Epoch 85/100
804/804 - 3s - 3ms/step - accuracy: 0.7025 - loss: 0.5955
Epoch 86/100
804/804 - 2s - 3ms/step - accuracy: 0.7021 - loss: 0.5955
Epoch 87/100
804/804 - 2s - 2ms/step - accuracy: 0.7021 - loss: 0.5954
Epoch 88/100
804/804 - 2s - 3ms/step - accuracy: 0.7023 - loss: 0.5957
Epoch 89/100
804/804 - 3s - 3ms/step - accuracy: 0.7022 - loss: 0.5956
Epoch 90/100
804/804 - 2s - 3ms/step - accuracy: 0.7023 - loss: 0.5955
Epoch 91/100
804/804 - 2s - 3ms/step - accuracy: 0.7021 - loss: 0.5955
Epoch 92/100
804/804 - 2s - 3ms/step - accuracy: 0.7020 - loss: 0.5955
Epoch 93/100
804/804 - 2s - 3ms/step - accuracy: 0.7023 - loss: 0.5956
Epoch 94/100
804/804 - 2s - 2ms/step - accuracy: 0.7020 - loss: 0.5956
Epoch 95/100
804/804 - 2s - 2ms/step - accuracy: 0.7020 - loss: 0.5958
Epoch 96/100
804/804 - 2s - 2ms/step - accuracy: 0.7023 - loss: 0.5957
Epoch 97/100
804/804 - 2s - 3ms/step - accuracy: 0.7020 - loss: 0.5958
Epoch 98/100
804/804 - 2s - 2ms/step - accuracy: 0.7020 - loss: 0.5955
Epoch 99/100
804/804 - 2s - 2ms/step - accuracy: 0.7021 - loss: 0.5956
Epoch 100/100
804/804 - 2s - 2ms/step - accuracy: 0.7023 - loss: 0.5955

In [42]:
# Ensure the input data has the correct shape
X_test_scaled_corrected = X_test_scaled[:, :number_input_features]

# Evaluate the model using the corrected test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled_corrected, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - 4ms/step - accuracy: 0.6988 - loss: 0.6039
Loss: 0.6038953065872192, Accuracy: 0.6987755298614502

In [43]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.